@startuml

class Acount
{
	Integer ID
	string Email
	string Pseudo
	string Password
}

class Profile
{
	Integer ID
	String FirstName
	String LastName
	Integer Age
	String ImageUrl
	ProfileType Type
	Acount acount
}

Acount -- Profile

enum ProgramType
{
	IMC
}

class Program
{
	Integer ID
	String Name
	ProgramType Type
	Profile Profile
}

Program -- ProgramType
Program -- Profile

enum TraitType
{
	POIDS
	TAILLE
}

class Trait
{ 
	Integer ID
	String value
	TratType Type
	DateTime Date
	Program Program
}

Trait -- TraitType
Trait -- Program

@enduml