@startuml

class Account
{
	Integer ID
	string Email
	string Pseudo
	string Password
}

class Profile
{
	Integer ID
	String FirstName
	String LastName
	Integer Age
	String ImageUrl
	Account acount
}

Account -- Profile

enum PlanType
{
	IMC
}

class Plan
{
	Integer ID
	String Name
	PlanType Type
	Profile Profile
}

Plan -- PlanType
Plan -- Profile

enum TraitType
{
	POIDS
	TAILLE
}

class Trait
{ 
	Integer ID
	String value
	TratType Type
	DateTime Date
	Plan Plan
}

Trait -- TraitType
Trait -- Plan

@enduml